require 'date'
require 'yaml'
require 'faker'

require_relative 'validator'
require_relative 'storage'
require_relative '../lib/entities/author'
require_relative '../lib/entities/book'
require_relative '../lib/entities/order'
require_relative '../lib/entities/reader'
require_relative '../lib/library'
require_relative '../errors/errors'
